### ISSUE TITLE
Expose method to get public key from private key like in FIPS 204

### ISSUE THREAD

**Issue by codespree** [integritychain/slh-dsa-rs#4]
Hi,

As exposed in your FIPS 204 crate. A method to get the public key would be very helpful

Thanks.

**Comment by integritychain** [comment]
This is a recent addition:
https://docs.rs/fips205/0.4.0/fips205/slh_dsa_sha2_128f/struct.PrivateKey.html#method.get_public_key

Is it what you need?

**Comment by codespree** [comment]
Yes. Thanks!
